### PR TITLE
T์heNoblequran

### PR DESCRIPTION
**Pull request by MaedaSunthorn**
T์heNoblequran by Maeda

### CODE REVIEW

**Comment by langsari** [comment]
please do not TOUCH on master branch, working only on your branch

**Comment by langsari** [comment]
again, please do not TOUCH on master branch, working only on your branch

**Comment by langsari** [comment]
do not merge to master work only on your branches

**Comment by MaedaSunthorn** [comment]
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request merged**
