### PR TITLE
muhamad

### PR DESCRIPTION
**Pull request by moodxft**

### CODE REVIEW

**Comment by langsari** [comment]
I always monitoring, nice to see you here.

**Comment by langsari** [comment]
please work only on your own branch. DONT TOUCH the master branch. please respect other wells, got it?

**Comment by moodxft** [comment]
sorry teacher for that cause i don't know how to control about github i
just try to learn about it
i try to figure the program how to work and how will to get result

>

**Comment by langsari** [comment]
> sorry teacher for that cause i don't know how to control about github i just try to learn about it i try to figure the program how to work and how will to get result
> […](#)

nice keep going, but with more caution, okay?

**Comment by moodxft** [comment]
inshallah teacher
i have question how do we submit this assignment?

**Comment by langsari** [comment]
You are up to here, which mean you done some part of the assignment, do a report and submit via submission in google classroom

**Comment by moodxft** [comment]
what write in the report the step i did ?

>

**Pull request merged**
